# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [45]:
#%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [46]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [47]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [48]:
from sklearn import datasets
iris = datasets.load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [49]:
X = iris.data
y = iris.target
print(X.shape)
print(y.shape)
X
y

(150, 4)
(150,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [50]:
from sklearn.model_selection import train_test_split
from scipy.stats import zscore
from scipy import stats
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)
X_train_z = stats.zscore(X_train) 
X_test_z = stats.zscore(X_test)
X_train.shape

(112, 4)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [51]:
trainY = tf.keras.utils.to_categorical(y_train, num_classes=3)
testY = tf.keras.utils.to_categorical(y_test, num_classes=3)


## Question 5

### Initialize a sequential model
- Define a sequential model

In [52]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Normalize the data
#model.add(tf.keras.layers.BatchNormalization())

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [53]:

#Add OUTPUT layer
model.add(tf.keras.layers.Dense(3,input_shape=(4,), activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [54]:
#Compile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', 
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [56]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [ ]:
'''
Since there 4 features and 3 labels, thus traininable parameters become 3x4 + 3 = 15 parameters
'''

## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [59]:
model.fit(X_train,trainY,          
          validation_data=(X_test,testY),
          epochs=100,
          batch_size=10)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 558us/sample - loss: 0.3203 - accuracy: 0.9375 - val_loss: 0.4129 - val_accuracy: 0.7632
Epoch 2/100
112/112 [==============================] - 0s 279us/sample - loss: 0.3178 - accuracy: 0.9107 - val_loss: 0.3874 - val_accuracy: 0.8421
Epoch 3/100
112/112 [==============================] - 0s 279us/sample - loss: 0.3148 - accuracy: 0.9286 - val_loss: 0.3660 - val_accuracy: 0.8684
Epoch 4/100
112/112 [==============================] - 0s 723us/sample - loss: 0.3114 - accuracy: 0.9375 - val_loss: 0.3811 - val_accuracy: 0.8684
Epoch 5/100
112/112 [==============================] - 0s 599us/sample - loss: 0.3118 - accuracy: 0.9464 - val_loss: 0.3808 - val_accuracy: 0.8684
Epoch 6/100
112/112 [==============================] - 0s 605us/sample - loss: 0.3090 - accuracy: 0.9464 - val_loss: 0.3967 - val_accuracy: 0.7895
Epoch 7/100
112/112 [==============================] - 0s 514us/sample - 

112/112 [==============================] - 0s 393us/sample - loss: 0.2666 - accuracy: 0.9375 - val_loss: 0.3170 - val_accuracy: 0.9474
Epoch 57/100
112/112 [==============================] - 0s 357us/sample - loss: 0.2683 - accuracy: 0.9464 - val_loss: 0.3313 - val_accuracy: 0.8684
Epoch 58/100
112/112 [==============================] - 0s 265us/sample - loss: 0.2639 - accuracy: 0.9554 - val_loss: 0.3558 - val_accuracy: 0.8421
Epoch 59/100
112/112 [==============================] - 0s 204us/sample - loss: 0.2649 - accuracy: 0.9643 - val_loss: 0.3498 - val_accuracy: 0.8421
Epoch 60/100
112/112 [==============================] - 0s 266us/sample - loss: 0.2622 - accuracy: 0.9375 - val_loss: 0.2925 - val_accuracy: 0.9474
Epoch 61/100
112/112 [==============================] - 0s 515us/sample - loss: 0.2640 - accuracy: 0.9554 - val_loss: 0.3266 - val_accuracy: 0.8947
Epoch 62/100
112/112 [==============================] - 0s 398us/sample - loss: 0.2610 - accuracy: 0.9554 - val_loss: 0.3544 

## Question 10

### Make predictions
 Predict labels on one row

In [85]:
pred = model.predict(X_test)
print ("Predicted value", pred[4,:])

import numpy as np
predicted_num = np.argmax(pred[4])

#Print the number
print("Predicted Label: ",predicted_num)

Predicted value [0.00211538 0.33162868 0.666256  ]
Predicted Label:  2


### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [69]:
print ("Input feature set: ",X_test[4])
print ("Actual Label: ",y_test[4])


Input feature set:  [7.9 3.8 6.4 2. ]
Label:  2


# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [87]:
#%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [88]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [89]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()

In [133]:
import numpy as np
import pandas as pd

df = pd.read_csv("prices.csv")
print(df.shape)
df.head()

(851264, 7)


date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   
2  2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000  119.739998   
3  2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000  117.440002   
4  2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996  117.330002   

      volume  
0  2163600.0  
1  2386400.0  
2  2489500.0  
3  2006300.0  
4  1408600.0

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [134]:
df2 = df.drop(columns = ['date','symbol'])
df2.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [135]:
df1000 = df2.iloc[0:1000,:]
df1000.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [139]:
y= df1000['volume']
X= df1000.drop(columns='volume')
y_norm = y/1000000
y_norm

0       2.1636
1       2.3864
2       2.4895
3       2.0063
4       1.4086
5       1.0980
6       0.9496
7       0.7853
8       1.0937
9       1.5235
10      1.6539
11      0.9443
12      0.7449
13      0.7038
14      0.5631
15      0.8961
16      0.6804
17      0.7499
18      0.5742
19      0.6948
20      0.8963
21      0.9563
22      0.9971
23      1.2005
24      1.7252
25      1.9460
26      1.3195
27      0.9224
28      1.1851
29      0.9215
        ...   
970     9.0975
971     2.2421
972     6.2051
973     0.8646
974     0.7092
975     1.1296
976     3.4493
977     7.5171
978     2.3565
979     4.8392
980     3.6846
981    14.4284
982     1.4633
983     0.7496
984    13.3551
985    11.5383
986     9.9313
987    12.9060
988     0.3699
989     2.7010
990     2.6278
991     3.2587
992     5.2061
993     7.0990
994     7.7955
995     2.1332
996     1.9824
997    37.1528
998     6.5686
999     5.6043
Name: volume, Length: 1000, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [140]:
labels = np.array(y_norm).astype('float32')
features = np.array(X).astype('float32')
labels


array([2.163600e+00, 2.386400e+00, 2.489500e+00, 2.006300e+00,
       1.408600e+00, 1.098000e+00, 9.496000e-01, 7.853000e-01,
       1.093700e+00, 1.523500e+00, 1.653900e+00, 9.443000e-01,
       7.449000e-01, 7.038000e-01, 5.631000e-01, 8.961000e-01,
       6.804000e-01, 7.499000e-01, 5.742000e-01, 6.948000e-01,
       8.963000e-01, 9.563000e-01, 9.971000e-01, 1.200500e+00,
       1.725200e+00, 1.946000e+00, 1.319500e+00, 9.224000e-01,
       1.185100e+00, 9.215000e-01, 4.409000e-01, 1.244300e+00,
       6.813000e-01, 4.112000e-01, 4.473000e-01, 5.592000e-01,
       4.599000e-01, 9.716000e-01, 6.941000e-01, 1.159600e+00,
       8.847000e-01, 6.920000e-01, 8.980000e-01, 8.445000e-01,
       7.965000e-01, 4.168000e-01, 5.902000e-01, 4.951000e-01,
       5.158000e-01, 5.621000e-01, 8.093000e-01, 1.607300e+00,
       1.001300e+00, 7.114000e-01, 4.442000e-01, 5.341000e-01,
       7.982000e-01, 5.910000e-01, 4.432000e-01, 5.780000e-01,
       7.651000e-01, 5.143000e-01, 1.150000e+00, 2.0353

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [141]:
feat_norm = tf.math.l2_normalize(features)
feat_norm




<tf.Tensor: id=16765, shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [142]:
#We are initializing weights and Bias with Zero
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [143]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [144]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [145]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [146]:
for i in range(100):
    
    w, b = train(feat_norm, labels, w, b)
    print('Current Loss on iteration', i, loss(labels, prediction(feat_norm, w, b)).numpy())

Current Loss on iteration 0 236.16759
Current Loss on iteration 1 235.09299
Current Loss on iteration 2 234.06102
Current Loss on iteration 3 233.06998
Current Loss on iteration 4 232.11783
Current Loss on iteration 5 231.20381
Current Loss on iteration 6 230.32585
Current Loss on iteration 7 229.48265
Current Loss on iteration 8 228.67299
Current Loss on iteration 9 227.89539
Current Loss on iteration 10 227.14832
Current Loss on iteration 11 226.43114
Current Loss on iteration 12 225.74234
Current Loss on iteration 13 225.0808
Current Loss on iteration 14 224.44554
Current Loss on iteration 15 223.83499
Current Loss on iteration 16 223.24931
Current Loss on iteration 17 222.68657
Current Loss on iteration 18 222.14594
Current Loss on iteration 19 221.62688
Current Loss on iteration 20 221.12842
Current Loss on iteration 21 220.6498
Current Loss on iteration 22 220.18993
Current Loss on iteration 23 219.7484
Current Loss on iteration 24 219.32425
Current Loss on iteration 25 218.91705

### Observe values of Weight
- Print the updated values

In [147]:
print('Weights:\n', w.numpy())


Weights:
 [[0.05478281]
 [0.05488191]
 [0.05422735]
 [0.05533117]]


### Observe values of Bias
- Print the updated values

In [148]:
print('Bias:\n',b.numpy())

Bias:
 [4.607657]
